import * as vscode from "vscode";

export function activate(context: vscode.ExtensionContext) {
	vscode.window.showInformationMessage("Easy Alt Extension Activated!!!!");

	const provider = vscode.languages.registerCompletionItemProvider(
		["html", "jsx", "tsx"],
		{
			provideCompletionItems(
				document: vscode.TextDocument,
				position: vscode.Position
			) {
				const linePrefix = document
					.lineAt(position)
					.text.substring(0, position.character);

				if (!linePrefix.includes('alt="') && !linePrefix.includes("alt='")) {
					return undefined;
				}

				const suggestions = [
					"A mountain landscape with snow-capped peaks",
					"A modern kitchen with stainless steel appliances",
					"A group of people collaborating in an office meeting",
				].map((text) => {
					const completion = new vscode.CompletionItem(
						text,
						vscode.CompletionItemKind.Value
					);
					completion.insertText = text;
					completion.detail = "AI Generated Alt Text";
					completion.documentation = new vscode.MarkdownString(
						`Preview: ${text}\n\n*Generated by Easy Alt*`
					);
					completion.sortText = "0";
					return completion;
				});

				return suggestions;
			},
		},
		'"',
		"'"
	);

	let disposable = vscode.commands.registerCommand(
		"easy-alt.generateAlt",
		() => {
			const editor = vscode.window.activeTextEditor;
			if (!editor) {
				return;
			}

			vscode.commands.executeCommand("editor.action.triggerSuggest");
		}
	);

	context.subscriptions.push(provider, disposable);
}
